### ISSUE TITLE
July PresCat update

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#107]
_PresCat.Project_category edits_
- [ ] Move Belmont Crossing [NL000037] to category 1
- [ ] Move Worthington Woods Apts [NL000197] to category 4
- [ ] Rename "Portner Place" [NL000243] to "Portner Flats (Portner Place)"

**Comment by ptatian** [comment]
@mcohenui @npstrayer Starting a new issue for next month's update with some of the items from today's meeting.

**Comment by ptatian** [comment]
@mcohenui @npstrayer Sorry, did the Catalog updates for this month get run? I don't see any programs on L:. Let me know if you have any questions.

**Comment by mcohenui** [comment]
@ptatian @npstrayer Hi Peter. Neither the Sec8 MF nor the MFIS data were updated from June. It was still data from the end of May.

**Comment by ptatian** [comment]
OK, that's fine. But we should have noted that in the issue (as you have done now) and then closed it to indicate that the work was completed. I assumed the changes to PresCat.Project_category noted at the beginning of the issue were made? Thanks!

**Comment by ptatian** [comment]
@mcohenui @npstrayer Hi guys, I checked the PresCat.Project_category data set and the three manual changes at the top of this issue were not made. If we could please make those changes then we can close this issue. 

As a reminder, here are [the instructions for updating project categories](https://urbanorg.app.box.com/notes/45548238609). Recently, I've also updated the system so that the project names for the Catalog reports and export files will be taken from the Project_category data set. So, project name changes can be made directly to this file.
