### ISSUE TITLE
Add missing buildings and parcels for current projects based on MAR unit counts

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#110]
This task involves adding new building addresses to PresCat.Building_geocode and new parcel records to PresCat.Parcel so that the MAR building counts will more closely match what we have currently in Proj_units_total. (This is a precursor task to issue #114, where we will incorporate the MAR unit counts directly into the Project data set.) 

The MAR data relates to Project via the Building_geocode data set. The code below does a comparison and lists projects where the MAR unit count differs from the current Project proj_units_tot count by 5 units or more. 

```
proc sql noprint;
  create table Bldg_units_mar as
  select coalesce( a.bldg_address_id, b.address_id ) as bldg_address_id, 
    a.nlihc_id, b.active_res_occupancy_count as Bldg_units_mar
  from PresCat.Building_geocode as a 
  left join Mar.Address_points_2016_01 as b
  on a.bldg_address_id = b.address_id
  order by nlihc_id, bldg_addre;
quit;

proc summary data=Bldg_units_mar;
  by nlihc_id;
  var Bldg_units_mar;
  output out=Proj_units_mar (drop=_type_ _freq_) sum=Proj_units_mar;
run;

proc compare base=PresCat.Project compare=Proj_units_mar
    listall maxprint=(400,32000)
    method=absolute criterion=5;
  id nlihc_id;
  var proj_units_tot;
  with proj_units_mar;
run;
```

206 / 367 project unit counts differ by 5% or more. Another 2 projects have a missing Proj_units_mar value. This is likely because not all of the buildings/addresses are currently identified completely for every project in the Building_geocode data set. For example, project NL000028 has only one address in Building_geocode and one parcel in Parcel, but checking RealProp.Parcel_base file for similar owners reveals 5 parcels that are likely part of this property. 

```
proc print data=RealProp.Parcel_base;
  where ownername =: "ATLANTIC GARDENS";
  id ssl;
  var ownername premiseadd;
run;

    SSL                             OWNERNAME                         PREMISEADD

6168    0041    ATLANTIC GARDENS REDEVELOPMENT LIMITED PARTNERSHIP    4009 3RD ST SE       
6168    0042    ATLANTIC GARDENS REDVELOPMENT LIMITED PARTNERSHIP     4011 3RD ST SE       
6207    0030    ATLANTIC GARDENS REDEVELOPMENT LIMITED PARTNERSHIP    4222 - 4228 4TH ST SE
6207    0031    ATLANTIC GARDENS REDEVELOPMENT LIMITED PARTNERSHIP    4212 - 4218 4TH ST SE
6207    0811    ATLANTIC GARDENS REDEVELOPMENT LIMITED PARTNERSHIP    4202 - 4208 4TH ST SE
```

Furthermore, three of these parcels have address ranges, so there could be multiple building addresses associated with each. 

For the 208 projects where Proj_units_mar differs from Proj_units_tot by 5 or more units or Proj_units_mar is missing/0, we should check RealProp.Parcel_base, as the example above, to see if there are other parcels that for the same owner that can be associated with the same project. Note that, for public housing, the owner will be "DC Housing Authority," or something similar, so this method cannot be used. There may be other generic owners like this, so only if the parcels are clearly part of the same project should we count them. 

Once the new list of parcels has been created, Mar.address_ssl_xref can be used to identify all of the addresses that need to be added to PresCat.Building_geocode. The data set Mar.address_ssl_xref contains a crosswalk between **SSL** in RealProp.Parcel_base and **address_id** in Mar.Address_points_2016_01.  

The final code should modify PresCat.Building_geocode by adding new addresses and modify PresCat.Parcel by adding new parcels.

**Comment by NealHumphrey** [comment]
A few comments from similar investigation in Housing Insights:

1) We have written some pre-processing code to turn address ranges into individual lists of addresses. We assume that if both numbers are even, every even number between the two numbers is a potential address; if one is even and one is odd, we assume very number in between is a possible address. We then search for each of these addresses in the MAR (if it doesn't appear we discard it assuming it's not a real address). 

2) In addition to missing MAR ids, there's also the possibility that the MAR unit count field is systematically wrong, especially since so over 50% of the projects differ. There is another data source for unit count from opendata.dc.gov that I am investigating; check back on this [Housing Insights issue](https://github.com/codefordc/housing-insights/issues/495) for an update once opendata.dc.gov resolves some issues with that data (corrupted mar id).

**Comment by ptatian** [comment]
Thanks, Neal. Agree that the possibility of inaccurate data in the MAR can't be ruled out. Let's both keep working on this and share findings.

**Comment by NealHumphrey** [comment]
@ptatian how were the records in the Building_geocode created in the first place? Besides hunting down missing addresses via the real_property data, are there any upstream methods that could be adjusted or added on to to get a more complete list of addresses?

**Comment by ptatian** [comment]
It has been a very ad hoc process. In most of the source data (such as from HUD) there is only one address listed for a project. Over time, we've added addresses for additional buildings as we've become aware of them but it hasn't been a priority. This is the first attempt to try to be more comprehensive about it.

**Comment by ptatian** [comment]
@npstrayer Just following up on our conversation earlier this week. As I mentioned, we do have some code that can be used to parse out address ranges and that may be useful for this task. We use the [%Rcasd_address_parse()](https://github.com/NeighborhoodInfoDC/DHCD/blob/master/Macros/Rcasd_address_parse.sas) macro for splitting up the address lists in the DHCD RCASD notices into individual address lines. You can use this macro directly by adding **%DCData_lib( DHCD )** to the top of your program, after %DCData_lib( PresCat ). Or, you could copy the **Rcasd_address_parse.sas** file into the PresCat\Macros folder. The latter would be better if we think we need to make changes to the macro to make it work with the property data. So, you might just want to test to see how the macro works "as is" before deciding. (I'm guessing the macro should work without any modifications, since the RCASD address lists are probably more complicated than the ones in the property data. But better to try and see.)

The macro is pretty straightforward to use. You just pass it a data set that has a variable with the address ranges that you want to parse out. It will create a new data set (with a name you specify) that has the individual addresses in separate rows. The syntax is:

%Rcasd_address_parse( data=_input-data-set_, out=_output-data-set_, addr=_address-list-variable_, id=_-optional-obs-id-variables_ )

A sample call might look like this:

`%Rcasd_address_parse( data=property_addr, out=property_addr_parsed, addr=premiseadd, id=ssl )`

So, you are giving it a data set called **property_addr**, which has the property address field **premiseadd** and the ID field **ssl**. The macro will create a new data set called **property_addr_parsed** that will have one row for each of the individual addresses parsed out from whatever ranges are in **premiseadd**, with the ID variables (**ssl**) and new variables **Address** (the individual address) and **Addr_num** (a sequential numbering of addresses within the original records). 

For example, if I were to give it this:
```
SSL            Premiseadd
0000    0000   1905-1911 Savannah Terr
```

It would give back this:
```
SSL            Address                Addr_num
0000    0000   1905 Savannah Terr         1   
0000    0000   1907 Savannah Terr         2   
0000    0000   1909 Savannah Terr         3   
0000    0000   1911 Savannah Terr         4   
```

Of course, these might not all be valid addresses in the real world. So, usually my next step would be to run these addresses through the geocoding macro to see if they match with actual addresses. Further details on using the geocoding macro [are here](https://urbanorg.app.box.com/file/59754340281) but a basic invocation would be:

`%DC_mar_geocode( data=property_addr_parsed, staddr=address, out=property_addr_parsed_geo)`

You can then see which addresses got an actual match. The quality of the input addresses will affect the geo matching, so a nonmatch might just be a badly formatted address rather than a non-existing address. 

Sorry for the long post. Please let me know if you have any questions.

**Comment by ptatian** [comment]
Hi @npstrayer. Just wanted to check in on your progress on this issue. Thanks.
