### ISSUE TITLE
Add Greenway Gardens to Catalog

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#119]
Greenway Gardens is a S8 moderate rehab project listed in the Pres Network agenda (section A) but is not currently listed in the Catalog. We should add this project to the Catalog. Looking at the real property records, here are the parcels and addresses for this project. 

```
    SSL           PREMISEADD                   ui_proptype                   OWNERNAME

5423    0008    336 37TH ST SE    Residential: Rental apartment building    336 37TH LLC
5423    0009    330 37TH ST SE    Residential: Rental apartment building    336 37TH LLC
5423    0010    324 37TH ST SE    Residential: Rental apartment building    336 37TH LLC
5423    0011    318 37TH ST SE    Residential: Rental apartment building    336 37TH LLC
5423    0012    312 37TH ST SE    Residential: Rental apartment building    336 37TH LLC
5423    0013    306 37TH ST SE    Residential: Rental apartment building    336 37TH LLC
5423    0014    300 37TH ST SE    Residential: Rental apartment building    336 37TH LLC
```

We do not currently have any detailed subsidy data. We may be able to obtain more information from DC Housing Authority.

**Comment by ptatian** [comment]
@Woliver01 [Updated instructions](https://urbanorg.app.box.com/notes/241579724470) for adding new projects to Catalog.

**Comment by ptatian** [comment]
Hi @Woliver01. Yes, I thought it might be better to have them as separate issues--so completing one before moving on to the next. But, if you think it would make more sense to combine them, then let me know.

**Comment by Woliver01** [comment]
@ptatian I can keep them separate, thanks for clarifying.

**Comment by ptatian** [comment]
Hi @Woliver01. How is everything going on this issue? Do you think we can try to wrap it up this week? Thanks.

**Comment by Woliver01** [comment]
@ptatian Yes, I can get this wrapped up this week.

**Comment by ptatian** [comment]
Hi @Woliver01. Following up on our conversation yesterday, Greenway Gardens appears to be a different property than Greenway Apts, which is already in the Catalog. Greenway Apts (NL000147) is a 470-unit LIHTC development consisting of 16 real property parcels (in square 5411) all owned by Greenway Apartments Lp. (For the full list of parcels, see **L:\Libraries\PresCat\Prog\PDFs\network\NL000147-detailed.pdf**.) 

As noted above, [Greenway Gardens](https://www.apartments.com/greenway-gardens-apartments-washington-dc/g7yf6jy/) is an 84-unit property on a different set of parcels (in square 5423) owned by 336 37TH LLC. 

Since these do appear to be different developments, I would go ahead and add Greenway Gardens, as defined above, to the Catalog. 

Let me know if that makes sense or if you still think there's some confusion about the two developments. Thanks! cc: @mcohenui

**Comment by ptatian** [comment]
Thanks, @Woliver01. That file is out of date and reflects some prior confusion about the two projects. We got some additional information on the WDC I tax credit pool that's reflected in the most recent Catalog data. I would not use the older information now. @mcohenui

**Comment by ptatian** [comment]
@Woliver01 Hi Will. Checking in on this issue. Have you made any progress? I'd like to get this wrapped up. Let me know if you need any help. Thanks.

**Comment by ptatian** [comment]
@Woliver01 Did this program get batch submitted on L: yet? It doesn't appear that it did as I don't see any LOG or LST files on L:.

**Comment by Woliver01** [comment]
@ptatian This program has been batch submitted and this issue is now closed.
