### ISSUE TITLE
November Prescat Update

### ISSUE THREAD

**Issue by npstrayer** [NeighborhoodInfoDC/PresCat#122]

**Comment by ptatian** [comment]
@npstrayer @mcohenui Glad that you've gotten started on this. For this month's update, you should charge time to 101362-0001-001 (DC AFFORD PRESV STRAT TOOL). Thanks.

**Comment by ptatian** [comment]
@npstrayer As I mentioned, we have a [list of Sanford portfolio projects](https://urbanorg.box.com/s/gam11q3ai0jzblgh5vr6dymdu74n2avn) that we should use to update the Catalog and agenda.

1. For any of the projects that are in this list and also in the Catalog, set the _category_code=1_ (manual edit in **Prescat.Project_category** using the **Edit_project_category.sas** program).

2. Add any missing projects to the list in the Sanford portfolio section of the agenda, whether they are in the Catalog or not. 

Thanks.
