### ISSUE TITLE
Add LIHTC projects at end of year 15 to expiring subsidy report

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#164]
LIHTC projects that are approaching the end of the first 15 years of their affordability need to be monitored for potential preservation risks. These projects should be added to the report generated by **Prog\Reports\Expiration_rpt.sas** to list LIHTC projects approaching the end of their first 15 years of affordability within the next 12 months.  

The end of the first 15 years for LIHTC projects is indicated by the _Compl_end_ var in **PresCat.Subsidy**.

**Comment by ptatian** [comment]
@Woliver01 This was an issue that I created last year but it fits with what we were asked today about adding a list of LIHTC projects nearing end of 15 and 30 year expiration dates to HFA section of the Preservation Network agenda. Would like to ask you to take a look at this and think about how to add the 15 year dates to the **Prog\Reports\Expiration_rpt.sas** output. Let me know once you've done that and if you have any questions. cc: @mcohenui

**Comment by ptatian** [comment]
@Woliver01 Just checking in to see if you had any questions about this task. cc: @mcohenui

**Comment by Woliver01** [comment]
@ptatian Hi Peter, was this similar to L:\DCdata\Libraries\RegHsg\Prog\Subsidized_unit_counts.sas ? Specifically the LIHTC section code?

**Comment by ptatian** [comment]
@Woliver01 Yes, similar. But, for this task, we want to distinguish between projects with upcoming 15-year and 30-year end dates for LIHTC, and we want to *list* individual projects in each group. Let me know if you still have questions.

**Comment by Woliver01** [comment]
Final Log: L:\Libraries\PresCat\Prog\Reports\Expiration_rpt.log
