### ISSUE TITLE
Greenway Gardens Fix

### ISSUE THREAD

**Issue by Woliver01** [NeighborhoodInfoDC/PresCat#178]

**Comment by Woliver01** [comment]
@ptatian One of the issues was that the csv files were moved to a different server somehow. The errors are gone but there are some still warnings, specifically: WARNING: SSL not found in Parcel_base; will not be saved.

**Comment by ptatian** [comment]
Thanks, @Woliver01. Yes, that warning will appear but it is more informational. If that is the only message you are seeing it should be fine. You can do a pull request and I can review.
