### ISSUE TITLE
Preservation Catalog March 2019 update

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#188]
_Note: If you have not previously done so, [clone the PresCat repo](https://help.github.com/desktop/guides/contributing-to-projects/cloning-a-repository-from-github-to-github-desktop/) to **D:\DCData\Libraries** before proceeding._
_Note: Do not close this issue until **all** the steps below have been completed._

## Apply updates to Catalog
- [x] [Create new branch](https://help.github.com/desktop/guides/contributing-to-projects/creating-a-branch-for-your-work/) **update-#**_n_ in GitHub Desktop for work on this issue (where _n_=issue number). 
- [x] [Create and test Sec8MF update program](https://urbanorg.app.box.com/notes/45544495689)
- [x] [Create and test MFIS update program](https://urbanorg.app.box.com/notes/48593611845)
- [ ] [Create and test REAC update program](https://urbanorg.app.box.com/notes/317426216726)
- [x] [Request review and finalize programs](https://urbanorg.app.box.com/notes/295752223069)
- [x] After code has been reviewed and approved, merge branch, sync to L:, and batch submit all programs updated above.
- [x] Copy full path names of SAS LOG files for **all L: drive batch submits** into the comments for this issue.  (Example: *Final SAS LOG: L:\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2018_01.log*)

## Run reports

- [x] Batch submit **L:\Libraries\PresCat\Prog\Reports\Expiration_rpt.sas**
- [x] Batch submit **L:\Libraries\PresCat\Prog\Updates\Update_real_property.sas**
- [x] Batch submit **L:\Libraries\PresCat\Prog\Reports\Real_property_rpt.sas**
- [x] Copy full path names of SAS LOG files for **all L: drive batch submits** into the comments for this issue.  (Example: *Final SAS LOG: L:\Libraries\PresCat\Prog\Reports\Expiration_rpt.log*)

## Finalize monthly meeting agenda and Catalog PDF

- [x] Review the output files from each of the updates run above. This includes
  - Prog\Updates\Update_Sec8mf_yyyy_mm_subsidy.pdf 
  - Prog\Updates\Update_Sec8mf_yyyy_mm_project.pdf
  - Prog\Updates\Update_MFIS_yyyy_mm_subsidy.pdf 
  - Prog\Updates\Update_MFIS_yyyy_mm_project.pdf
  - Prog\Updates\Update_REAC_2018_09.lst
  - Prog\Reports\Expiration_rpt_yyyymmdd.xls
  - Prog\Reports\Real_property_rpt_yyyymmdd.xls

- [x] Add info about latest updates (new expiration dates, ownership changes, etc.) to Preservation Network meeting agenda.
  - Move projects with subsidies expiring in the next year (Expiration_rpt_yyyymmdd.xls) that are currently in Catalog Category 5 to **section B** of the Preservation Network meeting agenda and [change their Catalog Category](https://urbanorg.app.box.com/notes/45548238609) to **2** (expiring subsidies). 
  - Mentions of new DHCD notices or real property events (Real_property_rpt_yyyymmdd.xls) should be added to the Preservation Network meeting agenda. In some cases, this may mean moving projects in Category 5 to **section D** of the Preservation Network meeting agenda and [changing their Category](https://urbanorg.app.box.com/notes/45548238609) to **4** (more information needed). 
- [x] Make final changes to [Category variable](https://urbanorg.app.box.com/notes/45548238609) to move projects to different sections of the Preservation Catalog, based on feedback from previous meeting. 

- [x] Create the [Catalog PDF report](https://urbanorg.app.box.com/notes/45624463637)
- [x] Send **updated agenda** and **Catalog PDF** to CNHED

## Final steps
- [x] [Update Preservation Catalog web site](https://urbanorg.app.box.com/notes/295939490660)
- [x] Make sure full path names of SAS LOG files for **all L: drive batch submits** have been entered into the comments for this issue. 
- [x] Close issue.

_Do not close this issue until **all** the steps above have been completed._

**Comment by ptatian** [comment]
Final SAS logs:
L:\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2019_02.log
L:\Libraries\PresCat\Prog\Updates\Update_MFIS_2019_02.log

**Comment by ptatian** [comment]
Final SAS logs:
L:\Libraries\PresCat\Prog\Reports\Expiration_rpt.log
L:\Libraries\PresCat\Prog\Updates\Update_real_property.log
L:\Libraries\PresCat\Prog\Reports\Real_property_rpt.log

**Comment by ptatian** [comment]
Final SAS logs:
L:\Libraries\PresCat\Prog\Reports\Monthly_rpt_export.log
L:\Libraries\PresCat\Prog\Pres_cat_web_export.log
L:\Libraries\PresCat\Prog\Pres_cat_web_pdfs.log

**Comment by ptatian** [comment]
Will will update PDFs on Preservation Catalog web site.

**Comment by Woliver01** [comment]
Final SAS logs:
L:\Libraries\PresCat\Prog\Pres_cat_web_export.log
L:\Libraries\PresCat\Prog\Pres_cat_web_pdfs.log

**Comment by Woliver01** [comment]
Hi @ptatian I updated the Preservation Catalog website.

**Comment by ptatian** [comment]
Thanks, @Woliver01!
