### ISSUE TITLE
Create programs for updating LIHTC projects

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#22]

**Comment by ptatian** [comment]
Hit an impasse because HUD source data for LIHTC projects only has year placed in service, not a date. We have dates for some from DHCD but then we don't want to overwrite those dates when the next HUD update is processed. Need to think about a solution.

**Comment by katyaabaz** [comment]
Not even a month attached to the year? Was this the subsidy for which we had January 1st as the start date for all of the properties?

**Comment by ptatian** [comment]
Yes, that's why so many of the tax credit start dates in the Catalog are January 1--because HUD only gives you the year. An added complication is that a project might a range of start dates, because individual properties in the project may have been put in service at different times. That's in the data that DHCD gave us referred to in issue #25.

**Comment by ptatian** [comment]
Next steps:

- [ ] Fix problem with multiple subsidy record matches
- [x] Modify new subsidy report to include all subsidy records in new file and traffic light new subsidy rows
- [ ] Add option for address corrections
- [ ] Add option for manual matches?
- [ ] Export unmatched update records for adding as new Catalog projects
- [ ] Verify final Subsidy file
- [ ] Create update Project file
- [ ] Create finalize data code
- [ ] Final testing
- [ ] Clean up code

**Comment by ptatian** [comment]
Need to incorporate code/process for adding unmatched (new) projects.
