### ISSUE TITLE
Preservation Catalog Dec 2021 update

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#272]
_Note: If you have not previously done so, [clone the PresCat repo](https://help.github.com/desktop/guides/contributing-to-projects/cloning-a-repository-from-github-to-github-desktop/) to **C:\DCData\Libraries** and pull latest changes from main branch before proceeding._
_Note: Do not close this issue until **all** the steps below have been completed._

## Apply updates to Catalog

- [x] [Create new branch](https://help.github.com/desktop/guides/contributing-to-projects/creating-a-branch-for-your-work/) **update-#**_n_ in GitHub Desktop for work on this issue (where _n_=issue number). 
- [x] [Create and test Sec8MF update program](https://urbanorg.app.box.com/notes/45544495689)
- [x] [Create and test MFIS update program](https://urbanorg.app.box.com/notes/48593611845)
- [x] [Create and test REAC update program](https://urbanorg.app.box.com/notes/317426216726)
- [x] [Request review and finalize programs](https://urbanorg.app.box.com/notes/295752223069)
- [x] After code has been reviewed and approved, merge branch, sync to `\\sas1\DCData\`, and batch submit all programs updated above.
- [x] Copy full path names of SAS LOG files for **all remote batch submits** into the comments for this issue.  (Example: `\\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2018_01.log`)

## Run reports

- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Expiration_rpt.sas`
- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_real_property.sas`
- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Real_property_rpt.sas`
- [x] Copy full path names of SAS LOG files for **all remote batch submits** into the comments for this issue.  (Example: `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Expiration_rpt.log`)

## Finalize monthly meeting agenda and Catalog PDF

- [x] Review the output files from each of the updates run above. This includes
  - Prog\Updates\Update_Sec8mf_yyyy_mm_subsidy.pdf 
  - Prog\Updates\Update_Sec8mf_yyyy_mm_project.pdf
  - Prog\Updates\Update_MFIS_yyyy_mm_subsidy.pdf 
  - Prog\Updates\Update_MFIS_yyyy_mm_project.pdf
  - Prog\Updates\Update_REAC_2018_09.lst
  - Prog\Reports\Expiration_rpt_yyyymmdd.xls
  - Prog\Reports\Real_property_rpt_yyyymmdd.xls

- [x] Add info about latest updates (new expiration dates, ownership changes, etc.) to Preservation Network meeting agenda.
  - Move projects with subsidies expiring in the next year (Expiration_rpt_yyyymmdd.xls) that are currently in Catalog Category 5 to **section B** of the Preservation Network meeting agenda and [change their Catalog Category](https://urbanorg.app.box.com/notes/45548238609) to **2** (expiring subsidies). 
  - Mentions of new DHCD notices or real property events (Real_property_rpt_yyyymmdd.xls) should be added to the Preservation Network meeting agenda. In some cases, this may mean moving projects in Category 5 to **section D** of the Preservation Network meeting agenda and [changing their Category](https://urbanorg.app.box.com/notes/45548238609) to **4** (more information needed). 
- [x] Make final changes to [Category variable](https://urbanorg.app.box.com/notes/45548238609) to move projects to different sections of the Preservation Catalog, based on feedback from previous meeting. 

- [x] Create the [Catalog PDF report](https://urbanorg.app.box.com/notes/45624463637)
- [x] Send **updated agenda** and **Catalog PDF** to CNHED

## Housing Insights export

- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Export_catalog_housing_insights.sas`
- [x] Put export files in `\\sas1\DCData\Libraries\PresCat\Raw\Housing Insights` into a .ZIP file and copy .ZIP file to [Box](https://urbanorg.app.box.com/folder/41956661492). 
- [x] Send an email to Scott and Michael to let them know updated data are available.

## Final steps

- [x] Make sure full path names of SAS LOG files for **all remote batch submits** have been entered into the comments for this issue. 
- [x] Close issue.

_Close this issue once all the steps above have been completed._

**Comment by Woliver01** [comment]
\\sas1\dcdata\Libraries\PresCat\Prog\Reports\Expiration_rpt.log
\\sas1\dcdata\Libraries\PresCat\Prog\Reports\Real_property_rpt.log
\\sas1\dcdata\Libraries\PresCat\Prog\Updates\Edit_project_category.log
\\sas1\dcdata\Libraries\PresCat\Prog\Updates\Update_real_property.log
\\sas1\dcdata\Libraries\PresCat\Prog\Updates\Update_MFIS_2021_11.log
\\sas1\dcdata\Libraries\PresCat\Prog\Updates\Update_REAC_2021_11.log
\\sas1\dcdata\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2021_12.log
