### ISSUE TITLE
Preservation Catalog Feb 2022 update

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#274]
_Note: If you have not previously done so, [clone the PresCat repo](https://help.github.com/desktop/guides/contributing-to-projects/cloning-a-repository-from-github-to-github-desktop/) to **C:\DCData\Libraries** and pull latest changes from main branch before proceeding._

## Apply updates to Catalog

- [x] [Create new branch](https://help.github.com/desktop/guides/contributing-to-projects/creating-a-branch-for-your-work/) **update-#**_n_ in GitHub Desktop for work on this issue (where _n_=issue number). 
- [x] [Create and test Sec8MF update program](https://urbanorg.app.box.com/notes/45544495689)
- [x] [Create and test MFIS update program](https://urbanorg.app.box.com/notes/48593611845)
- [x] [Create and test REAC update program](https://urbanorg.app.box.com/notes/317426216726)
- [x] [Request review and finalize programs](https://urbanorg.app.box.com/notes/295752223069)
- [x] After code has been reviewed and approved, merge branch, sync to `\\sas1\DCData\`, and batch submit all programs updated above.
- [x] Copy full path names of SAS LOG files for **all remote batch submits** into the comments for this issue.  (Example: `\\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2018_01.log`)

## Run reports

- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Expiration_rpt.sas`
- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_real_property.sas`
- [ ] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Real_property_rpt.sas`
- [ ] Copy full path names of SAS LOG files for **all remote batch submits** into the comments for this issue.  (Example: `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Expiration_rpt.log`)

## Finalize monthly meeting agenda and Catalog PDF

- [ ] Review the output files from each of the updates run above. This includes
  - Prog\Updates\Update_Sec8mf_yyyy_mm_subsidy.pdf 
  - Prog\Updates\Update_Sec8mf_yyyy_mm_project.pdf
  - Prog\Updates\Update_MFIS_yyyy_mm_subsidy.pdf 
  - Prog\Updates\Update_MFIS_yyyy_mm_project.pdf
  - Prog\Updates\Update_REAC_yyyy_mm.lst
  - Prog\Reports\Expiration_rpt_yyyymmdd.xls
  - Prog\Reports\Real_property_rpt_yyyymmdd.xls

- [ ] Add info about latest updates (new expiration dates, ownership changes, etc.) to Preservation Network meeting agenda.
  - Add new projects with subsidies expiring in the next year (Expiration_rpt_yyyymmdd.xls) to the Preservation Network meeting agenda and [change their Catalog Category](https://urbanorg.app.box.com/notes/45548238609) to **2** (expiring subsidies). 
  - Mentions of new DHCD notices or real property events (Real_property_rpt_yyyymmdd.xls) should be added to the Preservation Network meeting agenda. In some cases, this may mean moving projects in Category 5 to **section D** of the Preservation Network meeting agenda and [changing their Category](https://urbanorg.app.box.com/notes/45548238609) to **4** (more information needed). 
- [ ] If needed based on feedback from previous meeting, make final changes to [Category variable](https://urbanorg.app.box.com/notes/45548238609) to move projects to different sections of the Preservation Catalog. 

- [ ] Create the [Catalog PDF report](https://urbanorg.app.box.com/notes/45624463637)
- [ ] Send **updated agenda** and **Catalog PDF** to CNHED

## Housing Insights export

- [ ] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Export_catalog_housing_insights.sas`
- [ ] Put export files in `\\sas1\DCData\Libraries\PresCat\Raw\Housing Insights` into a .ZIP file and copy .ZIP file to [Box](https://urbanorg.app.box.com/folder/41956661492). 
- [ ] Send an email to Scott and Michael to let them know updated data are available.

## Final steps

- [ ] Make sure full path names of SAS LOG files for **all remote batch submits** have been entered into the comments for this issue. 

_Close this issue once all the steps above have been completed._

**Comment by ptatian** [comment]
@dharvey17 Although today's meeting is cancelled, I'd still like to wrap up this update so that we can start on the next one before the May meeting. In addition to batch submitting the data update files, it's worth submitting the report programs and taking a look at those and making any needed updates to the agenda. 

Since there is no meeting, you don't need to update the [Catalog PDF report](https://urbanorg.app.box.com/notes/45624463637) this time, but you could try those steps if you want to familiarize yourself with the process. 

I might skip the Housing Insights update this time as well, since we didn't have any major data updates. 

I'll set up another update for next month, which we should complete in time to update the agenda for the May 10 meeting. 

Thanks, Donovan. Let me know if you have questions.

**Comment by dharvey17** [comment]
MFIS
•	Log – \\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2022_01.log
•	Lst – \\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_ Sec8mf_2022_01.lst
REAC 
•	Log – \\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_REAC_2022_02.log
•	Lst – \\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_REAC_2022_02.lst

**Comment by ptatian** [comment]
Closing this issue. Update work will be completed under issue #278.
