### ISSUE TITLE
Figure out how to add new projects to the Catalog

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#28]
There is currently no procedure for adding a new project to the Catalog, which would involve assigning it a unique ID and adding records to the appropriate related data sets.

**Comment by ptatian** [comment]
Notes: https://urbanorg.app.box.com/notes/75277111378

**Comment by ptatian** [comment]
Hi @mcohenui, I finally have something that we can use to try adding new projects. I've placed two files with new tax credit developments on L:

```
L:\Libraries\PresCat\Raw\Buildings_for_geocoding_2017-05-25_main.csv
L:\Libraries\PresCat\Raw\Buildings_for_geocoding_2017-05-25_subsidy.csv
```
I followed the templates you sent me, but did make one change. I believe you were assuming that people would run the addresses through the MAR geocoder before inserting them into the template worksheets, right? If so, it seems you would also need the image and Google Streetview URLs to be included, so **I added those two columns to the _main template**. If I've misunderstood something about the process, I can take them out. 

So, please test these out and see how it works! I'd like to review before we finalize anything. 

FYI, I'm almost ready to push out the tax credit project updates using the DHCD FOIA data (issue #25). I'll want to finalize those updates before we finalize adding the new projects. I'll be sending a separate note about that shortly. 

Thanks, Mychal. Please let me know if you have any questions.

**Comment by mcohenui** [comment]
That is great news @ptatian. I will definitely carve out some time next week to start testing. Thanks for the update.

**Comment by ptatian** [comment]
Hi Mychal, Just FYI, I will need you to add the new LIHTC projects to the Catalog before I can finish issue #22. Thanks.

**Comment by ptatian** [comment]
@mcohenui As I mentioned, I made some modifications to the Project data set by adding three new variables:

- **proj_ayb** - Project year built (original)
- **proj_eyb** - Project year built (improvements)
- **proj_owner_type** - Project owner type (majority of parcels)

These variables will need to be filled in when adding new projects to the Catalog. Below is code that you can use to create these variables. This code assumes you are starting with complete Parcel data for one or more projects. In the example, I'm using the PresCat.Parcel file but it should also work if you substitute that with an updated parcel file for all the projects or just parcels for the new projects that you are adding. 

Similarly, at the end we merge the new variables back with the Project data. I'm using the PresCat.Project data set but you can substitute an updated temporary one. 

The program running this code needs to have access to both the PresCat and RealProp libraries. 

Let me know if you have any questions.

```
** Add year built to Project **;

proc sql noprint;
  create table Parcel_yb as
    select a.nlihc_id, coalesce( a.ssl, b.ssl ) as ssl, coalesce( a.ayb, b.ayb ) as ayb, coalesce( a.eyb, b.eyb ) as eyb
    from RealProp.Camarespt_2014_03 as b right join (
      select a.nlihc_id, coalesce( a.ssl, b.ssl ) as ssl, coalesce( a.ayb, b.ayb ) as ayb, coalesce( a.eyb, b.eyb ) as eyb
      from RealProp.camacondopt_2013_08 as b right join (
        select a.nlihc_id, coalesce( a.ssl, b.ssl ) as ssl, b.ayb, b.eyb
        from RealProp.camacommpt_2013_08 as b right join 
        PresCat.Parcel as a   /** Can replace PresCat.Parcel with a similar file **/
        on a.ssl = b.ssl ) as a 
      on a.ssl = b.ssl ) as a
    on a.ssl = b.ssl
    order by nlihc_id, ssl;
  quit;

data Parcel_yb_2;

  set Parcel_yb;
  
  if ayb < 1900 then ayb = .u;
  if eyb < 1900 then eyb = .u;

  label
    ayb = "Project year built (original)"
    eyb = "Project year built (improvements)";

  keep nlihc_id ayb eyb; 

  rename ayb=Proj_ayb eyb=Proj_eyb;

run;

proc summary data=Parcel_yb_2;
  by nlihc_id;
  var Proj_ayb Proj_eyb;
  output out=Project_yb (drop=_type_ _freq_) min=;
run;

** Add owner category to Project **;

proc summary data=PresCat.Parcel nway;     /** Can replace PresCat.Parcel with a similar file **/
  class nlihc_id parcel_owner_type;
  output out=Project_owner;
run;

proc sort data=Project_owner;
  by nlihc_id descending _freq_;
run;

data Project_owner_nodup;

  set Project_owner;
  by nlihc_id;
  
  if first.nlihc_id;

  label
    Parcel_owner_type = "Project owner type (majority of parcels)";

  keep nlihc_id Parcel_owner_type; 

  rename Parcel_owner_type=Proj_owner_type;

run;

data Project;

  merge
    PresCat.Project (in=in1)     /** Can replace PresCat.Project with a similar file **/
    Project_yb
    Project_owner_nodup;
  by nlihc_id;
  
  if in1;
  
run;
```

**Comment by mcohenui** [comment]
@ptatian I am wrapping up review of the add_subsidy program. In reviewing, I realized that there is code that formats the program variable (e.g. LIHTC/9PCT) into a umbrella variable called portfolio (e.g. LIHTC) using the $progtoportfolio format.

First question, is the subsidy data we are testing for 9%, 4% or both? 

Second question, how best do you think we should account for the range of ways one might input the program variable (e.g. LIHTC - 9% or LIHTC 9%), so that we consistently match to the progtoportfolio format? Would the best option be something like the streetalt.txt file? Or just provide a list of the correct format for the program variable in the instructions?

**Comment by ptatian** [comment]
Thanks, Mychal. I found out that the HUD LIHTC data identifies whether the tax credit subsidy is 4% or 9%. So, where possible, we want Program to be the specific one. Portfolio is meant to be broader groups, so any tax credit gets summarized there. 

The valid values for program for LIHTC will be
          'LIHTC/UNKWN' = 'Low income housing tax credit: unknown pct'
          'LIHTC/4PCT' = 'Low income housing tax credit 4%'
          'LIHTC/9PCT' = 'Low income housing tax credit 9%'
          'LIHTC/4+9PCT' = 'Low income housing tax credit 4+9%'
          'LIHTC/TCEP' = 'Low income housing tax credit: TCEP only'

(I made these changes to the formats in issue #22, which hasn't been merged yet so that's why the code on L: doesn't reflect them. But the formats actually have the new values.)

I think that it should be the responsibility of the person submitting the new projects to use the proper Program code. Your program should test whether the Program code is valid and report an error if not. The test can be whether the Portfolio value is missing. 

Let me know if that makes sense.

**Comment by mcohenui** [comment]
@ptatian Ah, ok, yes I was wondering why the code on L was displaying different values than the format folder in SAS. Yes, that definitely makes sense, and seems like the more straightforward option. I will make sure to note the program codes in the instructions.
