### ISSUE TITLE
Check public housing projects against HUD APSH.

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#29]
Verify list of public housing developments in Catalog with the HUD APSH list & HA data.

**Comment by ptatian** [comment]
Data updates from Housing Authority:
https://urbanorg.app.box.com/files/0/f/5613113065/1/f_61114608837
https://urbanorg.app.box.com/files/0/f/5613113065/1/f_61114608681

Some of these may  need to be entered into the subsidy exception file if they conflict with HUD data.

**Comment by ptatian** [comment]
@katyaabaz Would you please take a look at this and see if it's something you could take on? My recommendation would be to write a program that will change appropriate values in the Projects and Subsidy file records as needed. That way we will have documentation of the changes. You can test it locally before running the final version on SAS1, and I'd like to review before you finalize. Note that the procedures for updating files on SAS1 have changed a bit: https://urbanorg.app.box.com/notes/57065970009

The other potential issue is that if any of these records are being updated by the HUD Sec8 or MFIS files, then we'll need to do those changes as exceptions instead. (Exceptions override any updates from the HUD files.) This may only affect certain fields, like number of units or the project manager. We would need to look at that, too.

**Comment by katyaabaz** [comment]
@ptatian I'm just getting to look at this now and  I think I can definitely do this, but I'll need to familiarize myself with the exceptions process and the data a little more once we're back in the office.

**Comment by katyaabaz** [comment]
@rpitingolo I'm looking into the subsidy exceptions program, but I anticipate I'm going to need help with figuring out how to implement any changes in the Project/Subsidy programs. These procedures have been difficult for me to understand.

**Comment by katyaabaz** [comment]
Created a program for checking APSH against catalog data, unsure how to proceed with editing the subsidy_except file. 

See the program in the data-#29 branch - PresCat/Prog/Dev/Check_APSH_PH_062016.sas
