### ISSUE TITLE
Add new geographies to remaining Catalog data sets

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#291]
This issue follows #290 and is to add new Census, neighborhood cluster, and ward variables to the remaining PresCat data sets, which can be done using the updated Building_geocode data set.

**Comment by ptatian** [comment]
## Create a new program in C:\DCData\Libraries\PresCat\Prog\Dev

### Prescat.Project_geocode

The %Create_project_geocode() macro will produce a new version of Prescat.Project_geocode from Prescat.Building_geocode. The first step is to edit the macro source code (C:\DCData\Libraries\PresCat\Macros\Create_project_geocode.sas) to add the new variable names to the list in the _geo_vars_ macro variable. 

```
  %let geo_vars = Ward2012 Anc2012 Psa2012 Geo2010 Cluster_tr2000 Cluster_tr2000_name Zip;
```

Once that is done, in a new program you can invoke the macro to create the Project_geocode data set.

```
  %Create_project_geocode( revisions=%str(Add new Census geos, neighborhood clusters, and wards.)  )
```

The macro invokes the %Finalize_data_set() macro so there is no need for further code to finalize the data set. 

Note: DCData uses SAS autocall macros, meaning that SAS will automatially look for and load macro definitions from source code files without further user action. When working in interactive SAS (i.e., in the SAS Windows app), however, once a macro definition has been loaded during the session SAS will not reload the definition even if the source code is edited. If you make changes to the macro code during the session, you need to submit the new macro code to update the definition in memory. 

As a final check, you should run a local batch submit (on C:) to ensure that everything runs correctly. 

### Prescat.Project

In the same program you used above, merge the new variables from Project_geocode onto Prescat.Project by _nlihc_id_ to create a new temporary data set. This temporary data set can the be processed with the %Finalize_data_set() macro to replace the permanent, Prescat.Project data set.

```
%Finalize_data_set( 
  /** Finalize data set parameters **/
  data=Project,
  out=Project,
  outlib=PresCat,
  label="Preservation Catalog, Projects",
  sortby=nlihc_id,
  /** Metadata parameters **/
  revisions=%str(Add new Census geos, neighborhood clusters, and wards.),
  /** File info parameters **/
  printobs=0
)
```

**Comment by ptatian** [comment]
@eburton9 This is the next issue for you to work on, once you wrap up #290

**Comment by eburton9** [comment]
\\sas1\dcdata\Libraries\PresCat\Prog\Dev\Create_project_geocode
