### ISSUE TITLE
Add new geographies to Prescat.Project_category_view

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#292]
This issue is to add the new Census, neighborhood cluster, and ward variables to Prescat.Project_category_view, which uses and SQL query to dynamically join together the Project and Project_category data sets.

**Comment by ptatian** [comment]
@eburton9 Next issue after you finish up #291.

**Comment by eburton9** [comment]
\\sas1\DCDATA\Libraries\PresCat\Prog\Project_category_view
