### ISSUE TITLE
Update Catalog with HUD LIHTC 2020 data

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#293]
There are no instructions for LIHTC updates as of yet and the process requires manual checking to match projects. This first issue will update **existing** Catalog projects with the HUD LIHTC data. A subsequent issue will add **new** LIHTC projects to the Catalog.

**Comment by ptatian** [comment]
## Create Prog\Updates\Update_LIHTC_2020.sas

There is no template for this process but you can follow the model of 2013 update based on Prog\Updates\Update_LIHTC_2013.sas. Copy the 2013 program to C:\DCData\Libraries\PresCat\Prog\Updates and rename file to 2020.

Edit the program to replace 2013 with 2020 throughout. You also should delete the code after the manual_subsidy_match= and address_correct= parameters, but leaving the comma (,) between them. 

```
%Update_LIHTC( Update_file=Lihtc_2020, quiet=n,
  manual_subsidy_match=
  ,
  address_correct=
)
```

The next step is to submit this code and review the LOG and output.

**Comment by ptatian** [comment]
@dharvey17 Next issue to work on now that you have created the HUD LIHTC data set.

**Comment by ptatian** [comment]
@dharvey17 Need to batch submit Prog\Updates\Update_LIHTC_2020.sas on SAS1, review and copy LOG file here, and then close this issue.

**Comment by dharvey17** [comment]
\\sas1\DCDATA\Libraries\PresCat\Prog\Updates\Update_LIHTC_2020.log
