### ISSUE TITLE
Revise Catalog updating macro code to include new geographies

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#299]
For this task, you should review the code in the Macros folder and add the new geography variables as needed. For the most part, you will not be able to test this code as it is used during the data updating process. So again I will just need to review your changes.

**Comment by ptatian** [comment]
@eburton9 Next issue after #292.

**Comment by eburton9** [comment]
\\sas1\DCDATA\Libraries\PresCat\Macros\add_new_projects_geocode.sas
