### ISSUE TITLE
Add new LIHTC projects to Catalog from 2020 update

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#300]
Follow [instructions for adding new projects to Catalog](https://urbanorg.box.com/s/5o6ykm5q0cb9fcy9td6esjqqfk5ev3ql) to add new projects identified during LIHTC update.

**Comment by ptatian** [comment]
@dharvey17 I've updated the instructions for adding new projects to the Catalog (link in this issue). Please review and let me know what questions you have or if it would be helpful to go over it together. Thanks.

**Comment by ptatian** [comment]
@dharvey17 Subsidy information for new LIHTC projects was created by the update program (issue #293) and can be found here: \\sas1\DCData\Libraries\PresCat\Raw\AddNew\Update_Lihtc_2020_subsidy.csv  These data are copied to the template you create in step 6 of the update instructions.

**Comment by dharvey17** [comment]
Hi 
[@Donovan Harvey](https://theurbaninstitute.slack.com/team/U02QBUPRA58)
I've looked at the code for adding the LIHTC projects and everything seems fine, except for the two projects that were flagged as already in the Catalog.
New project Fendall Heights (NL001137) matches the location of Augusta Louisa Apts (NL000337), which we had previously marked as "Lost Rental" in the Catalog. It looks like the property was sold in 2013 and is part of a new scattered site development. So I think that this should be treated as a new project. The only issue, however, is that it looks like the previous LIHTC update program assigned a new 2014 tax credit to Augusta Louisa, and that credit should go to the new project instead. Here's my suggested fix:
Manually add a row to \\sas1\DCData\Libraries\PresCat\Raw\AddNew\New_projects_issue_300_subsidy.csv for address 52616 (Fendall Heights) with the tax credit that was assigned to Augusta Louisa. Fendall Heights would then have two separate tax credit records in that file.
Delete the tax credit subsidy record from Augusta Louisa. We'll do this in a separate issue.


New project Cedar Heights (NL001131) matches the location of existing project Finsbury Square Apts (NL000106). This one looks like it is the same project, too, but it is a little confusing. The ownership of the parcels in the real property data is listed as "Finsbury Square Limited Partnership."
A Google search, however, revealed that [Cedar Heights is an Enterprise project](https://cedarheights.enterpriseresidential.org/). Would you please follow up with our friends at Enterprise and see if you can confirm whether Cedar Heights is just a rebranded Finsbury Square Apts, or are they distinct projects? Thanks!

**Comment by ptatian** [comment]
Just noting here that Enterprise confirmed that Cedar Heights and Finsbury Square are the same project.
