### ISSUE TITLE
Add DC subsidy categories to Catalog

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#302]
@dharvey17 You can now start working on the next issue. As a first step to adding the local subsidies to the Preservation Catalog, we need to update the list of subsidy programs to include those that we don't have currently. This is done by modifying the **Prog\Make_formats.sas** program, which creates formats used to identify different subsidies. We'll be adding these subsidies: 

DC-FRPP - DC First Right Purchase Program
DC-HPF - DC Housing Preservation Fund
DC-LRSP - DC Local Rent Supplement Program 
DC-SAFI - DC SIte Acquisition Funding Initiative

###   $progfull

This format assigns a longer label to the code for the subsidy. The code will be the abbreviation above; the label will be the full program name. Look for the section of the Proc Format starting with `value $progfull`. You will add lines to this section for each of the new subsidies. An example is the Housing Production Trust Fund, which is already in the format (note that both values are enclosed in quotes):

`    'DC-HPTF' = 'DC housing production trust fund'`

###   $progshrt

This format assigns a short label to the code for the subsidy. This can be DC plus the program acronym. 

`    'DC-HPTF' = 'DC HPTF'`

###   $portfolio

Subsidies are also organized into groups called portfolios. This format labels those portfolios. For the new subsidies, we can make the portfolio the same as the subsidy. So, just copy the new lines you wrote for $progfull here. 

### $progtoportfolio

This last format is used to assign a subsidy code to a portfolio. Since the subsidies and portolios are the same for the new ones, you just need to have _code = code_. For example

`    'DC-FRPP' = 'DC-FRPP'`

### Testing code

Testing this code involves an extra step, since when you are doing the remote submits you cannot write to the format library on SAS1. So, as a temporary measure, you can add comment marks (/*...*/) around library name in Proc Format. 

`proc format /*library=PresCat*/;`

This will let you run Proc Format and see if there are any errors. You will still get an error for the Proc Catalog which follows in the program, but that code does not need to be changed so no need to test it. You can ignore any error from Proc Catalog.

When we are ready to finalize the code, you will remove the comment marks Proc Format and return it back to how it was. 

Let me know if you have any questions.

**Comment by dharvey17** [comment]
.log file: \\sas1\DCDATA\Libraries\PresCat\Prog\Make_formats.log
