### ISSUE TITLE
Update lost properties list

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#31]
Information from Kathryn Howell:
http://www.evernote.com/l/ASIuYhyvH5xCT4iP-VvDTut5lZZX_33gETw/

**Comment by katyaabaz** [comment]
@ptatian Just to double check - Should I manually change the project category for the list of properties, but just leave 1107 11th Street and New Amsterdam alone for now?

**Comment by ptatian** [comment]
Yes.

**Comment by katyaabaz** [comment]
@ptatian Elsinore Courtyards was on the "Lost" list, but we have it as "Expiring" so it's on the agenda. I'll make a note in the upcoming agenda.

**Comment by ptatian** [comment]
Perhaps follow up with Kathryn and Scott on Elsinore. It might have a complicated history. Thanks.

**Comment by katyaabaz** [comment]
I actually looked it up in the Agenda and it does note in the past meeting notes that because of a subset of units in the building, it was previously in Section 6, and the history from then on.

**Comment by ptatian** [comment]
Sounds good. Thanks!

**Comment by ptatian** [comment]
Katya, just checking, were these changes all made? If so, we should close this issue.

**Comment by katyaabaz** [comment]
Yes, moved to closed.
