### ISSUE TITLE
Update LIHTC project IDs to new format

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#318]
HUD has changed the ID numbers for the LIHTC projects by adding an extra 0 in the middle. DCB2004010 is now DCB20040010, DCB1988005 is DCB19880005, etc. So that we can properly match the Catalog and HUD data, we need to update the ID numbers in PresCat.Subsidy for LIHTC projects so that they match the new format.

**Comment by ptatian** [comment]
## Update_LIHTC_IDs.sas

Create a new program, **Prog\Dev\Update_LIHTC_IDs.sas**, to update the LIHTC IDs. This program will have a single [**data** step](https://libguides.library.kent.edu/SAS/DataStep) to create a temporary data set with the updated IDs and then use the %Finalize_data_set() macro to create the permanent data set on the final batch submit. 

The LIHTC project ID format is "DCB" + 4-digit year + a number with leading zeros. HUD has changed the last part from a 3-digit to a 4-digit number. We will use the SAS [substr()](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.2/lefunctionsref/n0n08xougp40i5n1xw7njpcy0a2b.htm), [input()](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.2/lefunctionsref/p19en16vskd2vhn1vwmxpxnglxxs.htm), and [put()](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.2/lefunctionsref/n0mlfb88dkhbmun1x08qbh5xbs7e.htm) functions to create the new IDs. 

```
data Subsidy;    /** This is the temporary data set we will create **/

  set Prescat.Subsidy;   /** Read in the existing Subsidy data set **/

  /** Only change LIHTC records that have a HUD project ID **/

  if portfolio = "LIHTC" and not( missing( subsidy_info_source_id ) ) then do;   
  
    /** Reformat IDs: 
            The first part takes the original 7 characters from the old ID.
            The second part reads the remaining characters as a number and reformats it
            as 4-character text with leading zeros (the z4. format).
            These two pieces are concatenated together (||) to make the new ID.
            The trim() and left() functions are used to remove trailing and leading blanks.
    **/

    subsidy_info_source_id = 
      trim( substr( subsidy_info_source_id, 1, 7 ) ) || 
      left( put( input( substr( subsidy_info_source_id, 8, 3 ), 3. ), z4. ) );

  end;

run;
```

In the next part of the program, use the %Finalize_data_set() macro. This macro will save the data set permanenty on the final batch submit and update the metadata system. 

```
%Finalize_data_set( 
  /** Finalize data set parameters **/
  data=Subsidy,
  out=Subsidy,
  outlib=PresCat,
  label="Preservation Catalog, Project subsidies",
  sortby=nlihc_id subsidy_id,
  /** Metadata parameters **/
  revisions=%str(Update LIHTC project IDs to new HUD format.),
  /** File info parameters **/
  printobs=0
)
```

**Comment by ptatian** [comment]
@dharvey17 I've created the issue for fixing the LIHTC IDs. This needs to be a separate branch from the one you were working on previously. Let me know if you have any questions.

**Comment by ptatian** [comment]
@dharvey17 For awareness, I probably overcomplicated the expression to create the new IDs. This would have worked just as well. 

```
    subsidy_info_source_id = 
      trim( substr( subsidy_info_source_id, 1, 7 ) ) || 
      "0" ||
      left( substr( subsidy_info_source_id, 8, 3 ) );
```

Because we just needed to stick an extra 0 in the ID number. But what we have is working so let's just keep it as is. Thanks!

**Comment by dharvey17** [comment]
\\sas1\DCDATA\Libraries\PresCat\Prog\Dev\Update_LIHTC_IDs.log
\\sas1\DCDATA\Libraries\PresCat\Prog\Dev\Update_LIHTC_IDs.lst
