### ISSUE TITLE
Attach characteristics from DCData databases to TOPA property database

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#321]
@eburton9 We'll be working with the [TOPA database](https://docs.google.com/spreadsheets/d/1xUxa8vBC8kZ3BLSiY8hv3LbrdvSGuF6SZfnfwzCMoIQ/edit?usp=sharing) compiled by the CNHED research associates. This data set is supposed to contain all the properties that have received a TOPA notice of some kind since 2006. Our goal is to match this database with DCData data sets so that we can add characteristics. 

The research associates added SSLs and other GEO IDs to the data, but I'd like to check that using our existing code, which I think should not be difficult. 

I'd suggest completing each step below and then checking your work as you go. Feel free to check in with me as you go along, if that would be helpful.

**Comment by ptatian** [comment]
### Steps

- [ ] Download and read the TOPA database into a SAS data set. You should create a unique identifier for each record in the input data set. (Could just be 1, 2, 3, etc.) 

- [ ] Use the %Rcasd_address_parse( ) macro to parse out the individual address from the lists in the field "All street address." 

This macro is part of the DHCD library, so you need to include the `%DCData_lib( DHCD )` line in your program to be able to access it. 

The macro uses these parameters, which must be provided: 
data=   Name of input data set, 
out=     Name of output data set, 
id=   Name of variable with unique identifier for each observation, 
addr=  Name of variable with list of addresses, 
keepin=  List of any other variables that you want to retain from the input data set (the list can be blank). You don't really need to keep all the variables in the input data but I would keep the "CASD Report week ending date" and "Offer of Sale date" as they will be needed later. 

What you will end up with in the out= data set is a list of individual addresses that were parsed out from the more complicated lists that are part of what are in the TOPA notices. 

- [ ] Run %DC_mar_geocode() geocoding macro on the list of individual addresses that you created above. This will add SSLs and GEO ids to the address list. [Instructions for using the geocoding macro](https://urbanorg.box.com/s/ppm1esbr4myde7t84ag84i52orejsuqj) are available on Box. 

- [ ] As noted in the geocoding instructions, the macro adds the parcel SSL, but that may not be all the SSLs associated with an address. Use the MAR.Address_ssl_xref address-parcel crosswalk data set to identify other parcels that should be matched to the address.

- [ ] Using the parcels (SSL) identified above, match property sales records in RealProp.Sales_master to the TOPA addresses. This will result in multiple matches per address. Retain only the sales records that have dates **after** "CASD Report week ending date" and "Offer of Sale date."

Let's get that far and see about next steps.

**Comment by ptatian** [comment]
@eburton9 Sorry, I should have said the above applies to the **TOPA-DOPA 5+** tab in the Google Sheet only.

**Comment by eburton9** [comment]
\\sas1\DCDATA\Libraries\PresCat\Prog\AddNew\TOPA_data_to_DC_data.sas
