### ISSUE TITLE
Preservation Catalog PresCat Dec 2022 update

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#326]
_Note: If you have not previously done so, [clone the PresCat repo](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-and-forking-repositories-from-github-desktop#cloning-a-repository) to **C:\DCData\Libraries**. Pull the latest changes from main branch before proceeding._

## Apply updates to Catalog

- [x] [Create new branch](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches#creating-a-branch) **update-#**_n_ in GitHub

- [x] [Create and test Sec8MF update program](https://urbanorg.app.box.com/notes/45544495689)

- [x] [Create and test MFIS update program](https://urbanorg.app.box.com/notes/48593611845)

- [x] [Create and test REAC update program](https://urbanorg.app.box.com/notes/317426216726)

- [x] [Request review and finalize programs](https://urbanorg.app.box.com/notes/295752223069)

- [x] After code has been reviewed and approved, merge branch, sync to `\\sas1\DCData\`, and batch submit all programs updated above.

- [x] Copy full path names of SAS LOG files for **all remote batch submits** into the comments for this issue.  (Example: `\\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2018_01.log`)

## Run reports

- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Expiration_rpt.sas`

- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Updates\Update_real_property.sas`

- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Real_property_rpt.sas`

- [x] Copy full path names of SAS LOG files for **all remote batch submits** into the comments for this issue.  (Example: `\\sas1\DCData\Libraries\PresCat\Prog\Reports\Expiration_rpt.log`)

## Finalize monthly meeting agenda and Catalog PDF

- [x] Review the output files from each of the updates run above. This includes

- Prog\Updates\Update_Sec8mf_yyyy_mm_subsidy.pdf 

- Prog\Updates\Update_Sec8mf_yyyy_mm_project.pdf

- Prog\Updates\Update_MFIS_yyyy_mm_subsidy.pdf 

- Prog\Updates\Update_MFIS_yyyy_mm_project.pdf

- Prog\Updates\Update_REAC_yyyy_mm.lst

- Prog\Reports\Expiration_rpt_yyyymmdd.xls

- Prog\Reports\Real_property_rpt_yyyymmdd.xls

- [x] Add info about latest updates to Preservation Network meeting agenda.

- Add new projects with subsidies expiring in the next 90 days and next year (Expiration_rpt_yyyymmdd.xls) to the HUD section of the agenda. Send a list of these new projects to the HUD resolution team in advance of the meeting.

- Add new REAC scores to the agenda. 

- Add new DHCD notices or real property events (Real_property_rpt_yyyymmdd.xls) to the agenda.  

- [x] Create the [Catalog PDF report](https://urbanorg.app.box.com/notes/45624463637).

- [x] Send updated agenda and Catalog PDF to Steve Glaude and Ryan Trout at CNHED.

## Housing Insights export

- [x] Batch submit `\\sas1\DCData\Libraries\PresCat\Prog\Export_catalog_housing_insights.sas`

- [x] Put export files in `\\sas1\DCData\Libraries\PresCat\Raw\Housing Insights` into a .ZIP file and copy .ZIP file [to Box](https://urbanorg.app.box.com/folder/41956661492). 

- [ ] Send an email to Ryan Trout and Michael Kalish to let them know updated data are available.

## Final steps

- [ ] Make sure full path names of SAS LOG files for **all remote batch submits** have been entered into the comments for this issue. 

_Close this issue once all the steps above have been completed._

**Comment by dharvey17** [comment]
SEC8MF:
\\sas1\DCDATA\Libraries\PresCat\Prog\Updates\Update_Sec8MF_2022_10.lst
\\sas1\DCDATA\Libraries\PresCat\Prog\Updates\Update_Sec8MF_2022_10.log

MFIS:
\\sas1\DCDATA\Libraries\PresCat\Prog\Updates\Update_MFIS_2022_10.lst
\\sas1\DCDATA\Libraries\PresCat\Prog\Updates\Update_MFIS_2022_10.log

REAC:
\\sas1\DCDATA\Libraries\PresCat\Prog\Updates\Update_REAC_2022_10.lst
\\sas1\DCDATA\Libraries\PresCat\Prog\Updates\Update_REAC_2022_10.log

**Comment by dharvey17** [comment]
\\sas1\DCDATA\Libraries\PresCat\Prog\Reports\Monthly_rpt_export.log
