### ISSUE TITLE
Preliminary analysis of notices with unique property IDs

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#338]
## Basic descriptive tables

Let's start with some basic descriptive tables. Use Prescat.Topa_notices_sales and Prescat.Topa_addresses to produce the following tables. 

1a. TOPA Notices of Sale (With Duplicates) by Ward and Year, 2006-2020
1b. TOPA Notices of Sale (With Duplicates) by Neighborhood Cluster and Year, 2006-2020

2a. TOPA Notices of Sale (Deduplicated) by Ward and Year, 2006-2020
2b. TOPA Notices of Sale (Deduplicated) by Neighborhood Cluster and Year, 2006-2020

3a. Residential Units in Properties with TOPA Notices of Sale by Ward and Year, 2006-2020
3a. Residential Units in Properties with TOPA Notices of Sale by Neighborhood Cluster and Year, 2006-2020

**Comment by ptatian** [comment]
Data prep

Generating tables

| | Total | 2006 | 2007 | 2008 | ... | 2020 |
| -- | -- | -- | -- | -- | -- | -- |    
| DC |
| Ward 1 |
| Ward 2 |
| ... |
| Ward 8 |

proc tabulate data= format=comma12.0 noseps missing;
  class ;
  var ;
  table 
    /** Rows **/
    ,
    /** Columns **/
    
  ;
  format ;
run;

**Comment by eburton9** [comment]
Closing from PR #363 \\sas1\dcdata\Libraries\PresCat\Prog\TOPA\TOPA_desc_tables.sas
