### ISSUE TITLE
Make edits to Prescat.Subsidy to adjust LIHTC subsidy records

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#345]
Need to make final fixes to the 2020 LIHTC update. First changes to **Prescast.Subsidy**:
- Add new tax credit record for Cedar Heights to Finsbury Square Apts (NL000106). 
- Add new tax credit record to Portner Flats (NL000243).
- Remove new tax credit record from Augusta Louisa (NL000337). 

One change to Prescat.Project_category
- Rename Finsbury Square Apts to Cedar Heights.

Instructions for these steps are below. 

***
### Changes to Prescat.Subsidy

This task involves three modifications to **Prescat.Subsidy**. We'll write one new SAS program to do all this, and all the steps I describe below will go into this new program. 

In **Prescat.Subsidy**, there is one row for each subsidy associated with a project. Here's a (made up) example. 

| Nlihc_id | Subsidy_id | Portfolio | Subsidy_source_info_date | _More variables_ |
| --- | --- | --- | --- | --- |
| NL000001 | 1 | LIHTC | 4/2/2018 | ... |
| NL000001 | 2 | CDBG| 5/7/2019 | ... |
| NL000002 | 1 | PUBHSG | . | ... |
| _and so on_ |

Each row is uniquely identified by Nlihc_id and Subsidy_id. Subsidy_id just numbers the subsidy records 1, 2, 3, ..., depending on how many subsidies are associated with the project. So to add the new subsidy rows we need to first figure out which number they should be. You can use Proc Print to display the subsidy records for the two projects we are interested in. 

```
proc print data=Prescat.Subsidy;
  where nlihc_id in ( 'NL000106', 'NL000243' );  /** Limit output to rows with these project IDs **/
  var nlihc_id subsidy_id program Subsidy_info_source Subsidy_source_info_date;  /** Limit output to these variables **/
run;
```

In the output, you'll see the listing of the subsidy rows, which tells us what the number should be of the next row for the project. For instance, if NL000106 currently has 3 rows, the next would by subsidy_id = 4. 

First is adding the new tax credit records for Cedar Heights/Finsbury Square Apts (NL000106) and Portner Flats (NL000243). To do this we need to create observations that will be added to the **Prescat.Subsidy** data set, which we will do using a DATA step. (For a basic overview of the SAS DATA step, see [this tutorial](https://libguides.library.kent.edu/SAS/DataStep) and [this video](https://www.youtube.com/watch?v=xv9sAMbSCek).)

```
data Subsidy_new_obs;

  set Prescat.Subsidy (obs=0);  /** Copy variables from Prescat.Subsidy, without any data **/

  /** Data that is the same for both projects **/

  Subsidy_source_info_date = ;

  Subsidy_source = "";

  /** New tax credit row for Cedar Heights/Finsbury Square Apts (NL000106) **/

  nlihc_id = "NL000106";

  subsidy_id = ???;  /** Fill in number for new subsidy row **/

  >>  add other variables here

  output;  /** Saves the row to the output data set **/

  /** New tax credit row for Portner Flats (NL000243) **/

  nlihc_id = "NL000243";

  subsidy_id = ???;  /** Fill in number for new subsidy row **/

  >>  add other variables here

  output;  /** Saves the row to the output data set **/

run;
```

You need to fill in the rest of the variable assignments based on the information for each of these LIHTC records that was in the HUD source data. Look at the CSV files that were generated by Prog/Updates/Update_LIHTC_2020.sas and are saved in the SAS1 Raw folder. 

The result of the above should be a new temporary SAS data set called **Subsidy_new_obs** that has 2 rows, one for each project/subsidy. 

Then we'll use a second data step to both add the new rows and delete the row we don't want and create a new temporary data set, Subsidy, which will eventually become the new version of Prescat.Subsidy. 

```
data Subsidy;

  set Prescat.Subsidy Subsidy_new_obs;  /** Listing two data sets here. Rows will be read from both into the new data set **/ 
  by nlihc_id subsidy_id;  /** Keeps the order of the rows sorted by these two vars **/

  /** Remove tax credit row for Augusta Louisa, which was added from 2020 HUD update **/
  if Nlihc_id = "NL000337" and Portfolio = "LIHTC" and year( Subsidy_source_info_date ) = 2020 then delete;
  
run;
```

The IF statement above deletes the row for Augusta Louisa (Nlihc_id = "NL000337") that is a tax credit (Portfolio = "LIHTC") and comes from the 2020 HUD update. Subsidy_source_info_date is a SAS date value, which codes the month, day, and year. To get just the year part of the date, we have to use the year( ) function. 

The last part of the program will finalize the process of replacing the Prescat.Subsidy data set. We have a special macro for this. 

```
/** Replace Prescat.Subsidy with new version **/

%Finalize_data_set( 
  /** Finalize data set parameters **/
  data=Subsidy,
  out=Subsidy,
  outlib=Prescat,
  label="Preservation Catalog, Project subsidies",
  sortby=nlihc_id subsidy_id,
  /** Metadata parameters **/
  revisions=%str(Fix new LIHTC subsidies for NL000106, NL000243, and NL000337.),
  /** File info parameters **/
  printobs=0
)
```

Most of the above is boilerplate, but the revisions= parameter is used to describe what changes were made to the data set. This information appears in the metadata for the data set. 

But there are also some subsidy information that is part of the Prescat.Project data set, so we need to replace that as well. Again, we have some standard code for this. 

```
/** Update subsidy vars in Prescat.Project **/

%Create_project_subsidy_update( data=Subsidy ) 

data Project;
  	merge Prescat.project Project_Subsidy_update;
	by nlihc_id;
run;

%Finalize_data_set( 
  /** Finalize data set parameters **/
  data=Project,
  out=Project,
  outlib=PresCat,
  label="Preservation Catalog, Projects",
  sortby=Nlihc_id,
  archive=N,
  /** Metadata parameters **/
  revisions=%str(Fix new LIHTC subsidies for NL000106, NL000243, and NL000337.),
  /** File info parameters **/
  printobs=0
)
```

Note that none of the permanent data sets on SAS1 get replaced while you are working with a copy of the program on your remote desktop. It is only when we do the final batch submit on SAS1 that the data sets will be replaced. That allows us to work on the program safely, without disturbing any of the permanent data. 

That's the entire program for modifying Prescat.Subsidy.

**Comment by ptatian** [comment]
@dharvey17 Tagging you on this new issue, which should be started after you finish issue #300. This should complete the work on adding the 2020 LIHTC projects to the Catalog.

**Comment by dharvey17** [comment]
\\sas1\DCDATA\Libraries\PresCat\Prog\Dev\345_edit_LIHTC_records.log
\\sas1\DCDATA\Libraries\PresCat\Prog\Dev\345_edit_LIHTC_records.lst
