### ISSUE TITLE
Create CBO spreadsheet for TA information

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#348]
We need to create a spreadsheet [like this mockup](https://docs.google.com/spreadsheets/d/1PeAsA5-mHlrJz_zlyWY8Kovi_k_98wfz/edit?usp=sharing&ouid=101012864185545505029&rtpof=true&sd=true) that the CBOs will use to update and enter information about TOPA TA activities. This issue will follow completion of issue #337.

**Comment by eburton9** [comment]
Updating CBO spreadsheet to include year built (AYB and EYB variables), number of units, and ward

**Comment by eburton9** [comment]
Prog: \\sas1\dcdata\Libraries\PresCat\Prog\TOPA\TOPA_CBO_spreadsheet.sas
Excel file: \\sas1\dcdata\Libraries\PresCat\Prog\TOPA\Topa_CBO_sheet_newsales.xlsx
