### ISSUE TITLE
Add affordable housing variables to TOPA database from Preservation Catalog

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#374]
Hi @eburton9 Here's the next issue on the TOPA study data. We need to add variables for housing subsidies to the TOPA notice data. This corresponds to item 7.d in the data analysis plan. For each unduplicated notice, we want to define the following:

- Number of affordable units with LIHTC placed in service before unduplicated notice date
- Number of affordable units with LIHTC placed in service within one year after unduplicated notice date
- Number of affordable units with federal project-based subsidies (section 8, etc.), placed in service before unduplicated notice date
- Number of affordable units with federal project-based subsidies, placed in service within one year after unduplicated notice date
- Number of affordable units with DC HPTF subsidies awarded within one year after unduplicated notice date
- Date of formation of limited equity cooperative

These data can be obtained from the Preservation Catalog, specifically, PresCat.Subsidy. (See file metadata 
 //sas1/DCData/Metadata/meta_prescat_subsidy.html) This file contains separate subsidy records for Preservation Catalog projects. The subsidy type is identified by the PROGRAM and PORTFOLIO variables. For LIHTC, you can use `portfolio = "LIHTC"`; for federal-project based, you can use `portfolio in ( "202/811", "PB8", "PRAC" )`; for HPTF, you can use `portolio in ( "DC HPTF" )`; for limited equity coops, you can use `portfolio = "LECOOP"`.

The date when the subsidy began is POA_START_ORIG or, if it is missing, POA_START. 

The trick is merging this information with the TOPA notices. You should use Proc SQL for this. The first step is identifiying which Catalog projects are represented in the TOPA data. Catalog projects are uniquely identified by NLIHC_ID. PresCat.Building_geocode has address IDs for all the buildings associated with a NLIHC_ID. You want to connect the TOPA notices to the one or more NLIHC_ID values by matching the TOPA addresses with the Preservation Catalog addresses. So this is another many-to-many match (full join) that requires SQL. 

Once you have a crosswalk with TOPA notice IDs and NLIHC_ID, you can merge on the subsidy data. Again, you'll want to use SQL so that you can set match conditions of the subsidy start date either being before or up to one year after the notice. (You'll recall we did something like this when we matched the property sales with the notices.) 

Well, I know that's a bit much so think about it and we can talk further. Thanks!

**Comment by eburton9** [comment]
Closing from PR #387 \\sas1\dcdata\Libraries\PresCat\Prog\TOPA\TOPA_add_subsidies.sas
