### ISSUE TITLE
Add vars to Prescat.Topa_realprop

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#376]
@eburton9 As a first step toward addressing the TOPA sales data issues, please add these variables from **Realprop.Sales_master** to **Prescat.Topa_realprop**: ownerpt_extractdat_first and ownerpt_extractdat_last.

**Comment by ptatian** [comment]
@eburton9 This issue is finished, correct? If so, please copy the name of the SAS1 LOG file in the comments and close the issue. Thank you.

**Comment by eburton9** [comment]
sas1//dcdata/PresCat/Prog/TOPA/TOPA_data_to_DC_data.sas
