### ISSUE TITLE
Fill in missing sales for TOPA notices

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#377]
@eburton9 Based on some investigation of issues raised by the CBOs (see issue #375), we need to adjust our approach for matching sales to properties in Prescat.Topa_notices_sales. Here are a couple of challenges and my thoughts on corrections. **This issue should only be be started after finishing issue #376.**

### Sale date is missing or out of range

In some cases, we are missing a sale because the entry in the OTR data (Realprop.Sales_master/Prescat.Topa_realprop) is missing the date of sale. Examples of this are ID=316 and ID=232. Also, our sale cutoff date of May 2022 is omitting things where actual sales took place, such as ID=1380. 

To address this, for cases where the sale date is missing, I believe that we can use ownerpt_extractdat_first as the date instead. This is the date when that observation first appeared in the OTR data. Please make the following changes in the Sales_by_property_dates data step in TOPA_match_notices_property.sas.

1. Make a new sale date variable that = saledate if not( missing( saledate ) ), and = ownerpt_extractdat_first otherwise. 
2. Create an actual_saledate variable, that = 1 if we are using saledate and = 0 if we are using ownerpt_extractdat_first. 
3. Change the WHERE statement in that same datastep to an IF statement; use the new sale date variable you created in 1 instead of saledate; and change the upper bound from '31may2022'd to '31mar2023'd.
4. Label new variables. Assign the dyesno. format to actual_saledate. 

Use the new sale date variable you created for all the code that follows, including the Combo data step where the notice and sale data are combined. But please keep the original saledate and ownerpt_extractdat_first variables in the final Topa_notices_sales data set. 

To see what effect the above is having, please print out the sales in the revised data set for ID's referenced above. 

There are a few other things to look at, but let's start here and see where this gets us. Let me know if you have any questions.

**Comment by eburton9** [comment]
\\sas1\dcdata\Libraries\PresCat\TOPA\TOPA_match_notices_propery.sas
