### ISSUE TITLE
Add missing parcel for ID=894, fix missed duplicate address for IDs=10004 and 10005

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#381]
@eburton9 Fixes to the above require changes to TOPA_data_to_DC_data.sas. For 894, SSL='0620    0893' was not in the MAR-SSL crosswalk. So the fix is to add it. 

Before the Proc SQL where we create TOPA_SSL, you need to create a new temporary data set from Mar.Address_ssl_xref that adds an observation for linking address ID 237132 to SSL '0620    0893'. There are diffent ways to do this, but I'd like you to create the new observation using a Data step with a datalines statement. (Please note that the number of spaces between the two numbers in the SSL is important.)

```
data Address_ssl_xref_new_obs;

  length ssl $ 17;

  infile datalines dlm=",";

  input address_id ssl;

datalines;
237132, 0620    0893
;
run;
```

Then, create the temporary data set with the cross walk by concatenating the original with new observation.

```
data Address_ssl_xref;

  set Mar.Address_ssl_xref Address_ssl_xref_new_obs;

run;
```

Finally, replace Mar.Address_ssl_xref with Address_ssl_xref in the Proc SQL. 

This should result in two sales being added to Topa_realprop for ID=894.

**Comment by ptatian** [comment]
For 10004 and 10005, the problem was a glitch in the geocoding macro that doesn't deal with some addresses very will. In this case, East Capitoal (E. Capital) wasn't processed correctly. 

We already have something in the program to deal with this. If you look for the comment "** Manually fix addresses that are not successfully geocoded (problem with geocoder) **;" you will find a data step where we can make manual geocoding corrections. We want to add an IF-THEN statement to assign address_id = 305753 to IDs = 10004 and 10005. (Don't use the Address_std var in this case.) 

Actually, there are some wonky things going on in the geocoding that I need to investigate further.

**Comment by eburton9** [comment]
\\sas1\dcdata\Libraries\PresCat\Prog\TOPA\TOPA_data_to_DC_data
