### ISSUE TITLE
Review public housing revisions

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/PresCat#71]
I've restored the 7/5/16 versions of the PresCat.Project and PresCat.Subsidy data sets, so that we can review the changes to the public housing records that were made under issue #29.

_Documents_

- [x] Review [list of projects from DCHA] (https://urbanorg.box.com/s/qtxs65ouz1x0dj5vhtvqjjwwzklbsf2p) with Kerry Smyser, to make sure we understand what types of projects these are. 

_General_

- [x] Put Prog\Updates\Update_DCHA_Document_2016_04.sas in the standard program template. [Note: This means that the final file updates will happen only when the program is batch submit on L:]
- [x] I recommend against reading and replacing a data set in a single data step. (Ex, data prescat.subsidy; set prescat.subsidy; ...) This can cause problems. Rather, create a temporary data set and then, in a separate step, copy over the original when ready to finalize.

_Subsidy codes_
_Some of the subsidies flagged as PUBHSNG may actually be project-based vouchers or moderate rehab projects. We currently don't have codes for these so we'll need to add them to  Prog\Make_formats.sas._

- [x] Add to $progfull: 

>    'S8-MR' = 'Sec 8 moderate rehabilitation'
>    'PBV' = 'Project-based vouchers'

- [x] Add to $progshrt:

>    'S8-MR' = 'Sec 8 MR'
>    'PBV' = 'PBV'

- [x] Add to $portfolio:

>    'PBV' = 'Project-based vouchers'

- [x] Add to $progtoportfolio:

>    'S8-MR' = 'PB8'
>    'PBV' = 'PBV'

- [x] Batch submit Prog\Make_formats.sas. [Note: you need to do this so that the formats are available for the next steps.] 

_PresCat.Subsidy_

- [x] Where new rows need to be added, use program code to do that. 
- [x] When needed, use the new Program field codes 'PBV' and 'S8-MR' for project-based vouchers and section 8 mod rehab, respectively.
- [x] After updating the Program field, you also have to update the Portfolio field: `Portfolio = put( Program, $progtoportfolio. );`
- [x] Review non-PUBHSNG subsidies before deleting to make sure that they should not be associated with a different project in the Catalog.
- [x] Set field subsidy_info_source = "DCHA Document" or "HUD/APSH" (depending on the source) for records that have been modified. 
- [x] Set field subsidy_info_source_date = '12apr2016'd (for DCHA) or {date of APSH file} (for APSH) for records that have been modified.  
- [x] Final data set must be sorted by nlihc_id and subsidy_id
- [ ] Include in the output a full listing (Proc Print) of all records that have been modified. 
- [x] For testing purposes, run a Proc Compare to review all file changes, directing output to an external HTML file so that it can be saved as documentation of file changes.

> ods html body="&_dcdata_default_path\PresCat\Prog\Update\Update_DCHA_Document_2016_04_subsidy_compare.html" style=Default; 
> proc compare base=PresCat.Subsidy compare={updated file} listall maxprint=(40,32000);
>   id nlihc_id subsidy_id;
> run;
> ods html close;

_PresCat.Project_

- [x] Set field update_dtm to the date/time of the program run. I usually do it this way: 

_At program start:_
>   %let Update_dtm = %sysfunc( datetime() );

_In data step, when modifying records:_
>   if ... then do; 
>   _...update fields..._ 
>  Update_Dtm = &Update_Dtm; 
>  end;

- [x] Be aware that changes to fields Hud_Mgr_Name and Hud_Own_Name may be overwritten if the project also has project-based subsidies in it. In that case, it may be appropriate to use the PresCat.Project_except data set for these changes instead.
- [x] Final data set must be sorted by nlihc_id
- [x] Include in the program output a full listing (Proc Print) of all records that have been modified. 
- [x] For testing purposes, run a Proc Compare to review all file changes, directing output to an external HTML file so that it can be saved as documentation of file changes.

> ods html body="&_dcdata_default_path\PresCat\Prog\Update\Update_DCHA_Document_2016_04_project_compare.html" style=Default; 
> proc compare base=PresCat.Project compare={updated file} listall maxprint=(40,32000);
>   id nlihc_id;
> run;
> ods html close;

_Other_

- [x] Review all of the remaining Catalog files for any records related to projects **deleted** from PresCat.Project. In some cases, records in these files may also need to be deleted. In other cases, they may need to be assigned to different projects. 

- PresCat.Parcel
- PresCat.Real_property
- PresCat.Reac_score
- PresCat.Project_category
- PresCat.Project_geocode
- PresCat.Building_geocode

- [x] All files that are modified during this process need to be updated in the metadata system using the %Dc_update_meta_file() macro after being finalized.

**Comment by katyaabaz** [comment]
Thanks for doing this Peter – I’ll review tomorrow.

Katya

**Comment by ptatian** [comment]
Pushed up a few programming corrections. Some data questions.

- NL000050: Are there tax credits? Catalog has tax credits but they weren't on the list given to DCHA. 
- NL000232: Are there PH units? Notes are unclear. Seems like if units are PBV then there is no PH.
- NL000264: Are there bonds and tax credits? Catalog has these listed.
- NL000301: What is the FHLB subsidy in DCHA's notes? Catalog has CDBG funding. Are they the same?
- NL000329: Are there bonds and Sec 8? Catalog has these listed.
- NL000388: Are there PBV and PH units? If both, how many PBV units?

Do you know the answers to these questions? If not, can you check with Kerry? 

There's still some programming changes to make so I'll have more tomorrow.

**Comment by ptatian** [comment]
When we update the Subsidy data set, there are certain Project data set summary variables (like Proj_Units_Assist_Max) that get updated directly from Subsidy. I've added that code to the program and pushed those changes. (Sorry, I hadn't explained this earlier.)

**Comment by ptatian** [comment]
Made some additional commits, which should allow us to go ahead and finalize all of this Monday.
